name: tokensgen
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.34.2
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.1
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.7.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - beartype==0.18.5
      - bitsandbytes==0.44.1
      - boto3==1.34.155
      - botocore==1.34.155
      - braceexpand==0.1.7
      - cachetools==5.5.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.3.0
      - cpm-kernels==1.0.11
      - cycler==0.12.1
      - cython==3.0.11
      - datasets==2.14.4
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.14.4
      - dill==0.3.7
      - distro==1.9.0
      - diffusers==0.31.0.dev0
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - ffmpy==0.4.0
      - filelock==3.15.4
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - gradio==5.9.0
      - gradio-client==1.5.2
      - grpcio==1.66.2
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.26.2
      - idna==3.7
      - imageio==2.36.1
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.2.0
      - iopath==0.1.10
      - jinja2==3.1.4
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.6
      - llvmlite==0.43.0
      - lmdb==1.5.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - modelscope==1.21.0
      - moviepy==2.1.1
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.15
      - networkx==3.3
      - ninja==1.11.1.1
      - numba==0.60.0
      - numpy==1.26.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai==1.57.4
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - orjson==3.10.12
      - packaging==24.1
      - pandas==2.2.2
      - peft==0.13.0
      - pillow==10.1.0
      - platformdirs==4.2.2
      - portalocker==3.0.0
      - proglog==0.1.10
      - protobuf==5.29.1
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.19
      - pytorch-lightning==2.3.3
      - pytz==2024.1
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rsa==4.9
      - ruff==0.8.3
      - s3transfer==0.10.2
      - safehttpx==0.1.6
      - safetensors==0.4.4
      - scikit-image==0.25.0
      - scikit-learn==1.5.2
      - scipy==1.14.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - shapely==2.0.6
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - tokenizers==0.21.0
      - tomlkit==0.13.2
      - torch==2.4.1
      - torchmetrics==1.4.1
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.47.0
      - triton==3.0.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - uvicorn==0.34.0
      - wandb==0.17.5
      - wcwidth==0.2.13
      - webdataset==0.2.86
      - websockets==14.1
      - werkzeug==3.0.4
      - xformers==0.0.28.post1
      - xxhash==3.4.1
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.9.4
      - zipp==3.19.2
